[phases.setup]
nixPkgs = ["python311", "sqlite", "gcc"]

[phases.install]
cmds = ["pip install --no-cache-dir -r requirements.txt"]

[phases.build]
cmds = ["echo 'Build completo'"]

[start]
cmd = "bash start.sh"